### PR TITLE
#12197 Add basemap chart

### PR DESCRIPTION
**Pull request by azapasnik**

### CODE REVIEW

**Comment by akukhar** [comment]
> storageClassName: local-path

1. storageClassNames are specific to clusters as they correspond to storage provisioners that may not exist in different clusters. I suggest removing storageClassNames definitions from at least online installations.
2. local-path is deprecated in our clusters.

```
$ k get storageclass
NAME                        PROVISIONER                     RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
local-path                  rancher.io/local-path           Delete          WaitForFirstConsumer   false                  335d
local-path-fast (default)   rancher.io/local-path-fast      Delete          WaitForFirstConsumer   false                  41d
local-path-regular          rancher.io/local-path-regular   Delete          WaitForFirstConsumer   false                  41d
$
```

@azapasnik

**Comment by akukhar** [comment]
disableWait, timeout, and disableWaitForJobs are logically bound. If you disableWait, please add a comment to avoid future questions stating, for example, how long installation/upgrade can really take.

@azapasnik

**Comment by akukhar** [comment]
Rendered names of PVCs differ from current non-perfect names present in k8s-01 cluster. There will be a duplication of the requested storage. Options are:
- Bringing new names into accordance with existing names
- Manually bringing current names with future helm-generated names

```
$ k get pvc -n dev-basemap
NAME                     STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
basemap-claim            Bound    pvc-d4cb6895-abaf-4c54-8530-6d65cc670bbc   500Gi      RWO            local-path-fast   2d23h
basemap-postgres-claim   Bound    pvc-ef026fbf-6987-4df3-b751-fb0d116926ee   3000Gi     RWO            local-path-fast   2d23h
tileserver-gl-claim      Bound    pvc-f3127e97-baab-4ba2-a23b-24e421a195bb   150Gi      RWO            local-path        276d
$ helm template --dry-run -n dev-basemap -f values.yaml -f values/values-dev.yaml --set-string k8s_cluster_flavor=k8s-01.kontur.io dev-basemap --show-only templates/pvc.yaml .
---
# Source: basemap/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-basemap-tileserver-pvc
  namespace: dev-basemap
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 150Gi
    limits:
      storage: 150Gi

  storageClassName: local-path
---
# Source: basemap/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-basemap-processor-pvc
  namespace: dev-basemap
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
    limits:
      storage: 500Gi
---
# Source: basemap/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-basemap-postgres-pvc
  namespace: dev-basemap
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3000Gi
    limits:
      storage: 3000Gi
$
```

@azapasnik

**Comment by akukhar** [comment]
The previous comment about the naming change applies to most resources, including ingresses that would change URLs. Please make clear why the change of `basemap` to `basemap-tileserver` is needed.

@azapasnik

**Review by akukhar — CHANGES_REQUESTED** [review]
Please check my four previous comments

**Comment by azapasnik** [comment]
> The previous comment about the naming change applies to most resources, including ingresses that would change URLs. Please make clear why the change of `basemap` to `basemap-tileserver` is needed.

I hope to run the new deployment along side with the old one to make sure that it works as expected. Then switch https://disaster.ninja/tileserver/ to new deployment and remove old one.

**Comment by azapasnik** [comment]
The same applies to all resources

**Comment by azapasnik** [comment]
> disableWait, timeout, and disableWaitForJobs are logically bound. If you disableWait, please add a comment to avoid future questions stating, for example, how long installation/upgrade can really take.

Copy-pasted it from osrm chart. Not really sure I need it.

**Comment by azapasnik** [comment]
> storageClassName: local-path
Removed.

> disableWait
Removed as well. Will see how it works without it. Will add it later if needed.

**Comment by akukhar** [comment]
> > The previous comment about the naming change applies to most resources, including ingresses that would change URLs. Please make clear why the change of `basemap` to `basemap-tileserver` is needed.
> 
> I hope to run the new deployment along side with the old one to make sure that it works as expected. Then switch https://disaster.ninja/tileserver/ to new deployment and remove old one.

See the numbers below. Now, nodes in the k8s-01 cluster do not have enough space to accommodate your approach. I had a call with @rkireyeu-kontur and explain high-level steps that I would take to migrate databases at milan, london, and paris PG clusters into k8s-01.kontur.io. During that process, RAID array on hardware nodes would have to be disassembled to add 3.5T of data.

That would make your migration possible too. I am reluctant to start the process, knowing I will not see it through. 

@azapasnik I suggest switching the discussion to one of the public channels in Slack.

```
pvc:
  tileStorageSize: 150Gi
  processorStorageSize: 500Gi
  postgresStorageSize: 3000Gi
```

```
$ for i in 1 2 3; do ssh hwn0${i}.k8s-01.kontur.io df -BG /opt/local-path-provisioner; done
Filesystem                           1G-blocks  Used Available Use% Mounted on
/dev/mapper/vg01-thin--provisioner01     2047G 1284G      764G  63% /opt/local-path-provisioner
Filesystem                           1G-blocks  Used Available Use% Mounted on
/dev/mapper/vg01-thin--provisioner01     2048G  909G     1139G  45% /opt/local-path-provisioner
Filesystem                           1G-blocks  Used Available Use% Mounted on
/dev/mapper/vg01-thin--provisioner01     2047G  474G     1574G  24% /opt/local-path-provisioner
$
```

**Review by i1shilyaev — APPROVED** [review]

**Pull request merged**
